server:
  port: 8000

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: caraxxx13@gmail.com
    password: tjxhgpspspezuqux
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:mysql://localhost:3306/sfdb?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1567
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.back.*.repository
  mapper-locations: classpath:mapper/*/*.xml

management:
  endpoints:
    web:
      cors:
        allowed-origins: "http://localhost:3000"
        allowed-methods: GET, POST, PUT, DELETE
        allowed-headers: "*"
        exposed-headers: "Authorization, Custom-Header"
        allow-credentials: true
        max-age: 3600


        
# OAuth 클라이언트 정보 설정
  security:
    oauth2:
      client:
        registration:
          google:  
            client-id: 360256300731-odu5dfeupc2d32nnc4d9tmai3gdmkjms.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:8000/user/login/google"
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://accounts.google.com/o/oauth2/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
            
          naver:
            client-id: oizN99Oi1Z5vhgeRLGMB
            client-secret: oEkoNiO2bk
            redirect-uri: http://localhost:8000/user/login/naver
            client-authentication-method: form
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 네이버 로그인 API에서 사용자 정보를 받는 속성 이름